name: CI FastAPI App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install --no-cache-dir --upgrade -r requirements.txt -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m unittest discover tests
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.8
      with:
        # Additional arguments to the sonarcloud scanner
        args: -Dsonar.organization=lauraijb -Dsonar.projectKey=fastAPIsemillero20223 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SECRET }}
